### アカウント登録
POST https://hdgdzdaacb.execute-api.ap-northeast-1.amazonaws.com/test/java-custom-test
Content-Type: application/json
Accept: application/json
spring.cloud.function.definition: registface

{
    "accountId": "aaaaaa1112",
    "faceimage": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

### 顔取得
POST https://hdgdzdaacb.execute-api.ap-northeast-1.amazonaws.com/test/java-custom-test
Content-Type: application/json
Accept: application/json
spring.cloud.function.definition: getfaces

{
    "accountId": "aaaaaa1112",
}


### アカウント削除
DELETE http://127.0.0.1:8080/accounts?id=aaaaaa1112
Accept: application/json

### Face一覧
GET https://hdgdzdaacb.execute-api.ap-northeast-1.amazonaws.com/test/java-custom-test?id=aaaa&faceId=cccc
Accept: application/json
spring.cloud.function.definition: message

### Face登録
POST https://hdgdzdaacb.execute-api.ap-northeast-1.amazonaws.com/test/java-custom-test
Accept: application/json
spring.cloud.function.definition: message

{
"account":{"accountId":"aaaaaa1112"} ,
"imageFormat": "jpg"
}
###